# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170630_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='GenreOptions',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
