# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_genres_genreoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='GenreOptions',
        ),
        migrations.AddField(
            model_name='genres',
            name='type',
            field=models.CharField(choices=[('ACT', 'action'), ('COM', 'comedy')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
