# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170630_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='id',
        ),
        migrations.AlterField(
            model_name='genres',
            name='type',
            field=models.CharField(choices=[('ACT', 'action'), ('COM', 'comedy')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
