# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170630_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genres',
            name='type',
            field=models.CharField(choices=[('ACT', 'action'), ('COM', 'comedy')], max_length=20),
        ),
    ]
