# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170630_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
