# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=250),
        ),
    ]
