# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(choices=[('sephardi', 'sephardi'), ('ashkenazi', 'ashkenazi'), ('mizrachi', 'mizrachi'), ('other', 'other')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='background',
            field=models.ManyToManyField(to='polls.Background'),
        ),
    ]
