# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170702_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='background',
            field=models.CharField(max_length=10),
        ),
    ]
