# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170721_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
