# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170721_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Gender'),
        ),
    ]
